// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCompactNudgesEnabled():Promise<boolean>;

export function GetHookHealth():Promise<main.HookHealth>;

export function GetOverview():Promise<main.Overview>;

export function GetPlatform():Promise<string>;

export function GetProjects():Promise<Array<main.ProjectRow>>;

export function GetSessionStats(arg1:string):Promise<Array<main.SessionRow>>;

export function RefreshClaudeHook():Promise<main.HookHealth>;

export function RefreshCodexHook():Promise<main.HookHealth>;

export function SetClaudeHookEnabled(arg1:boolean):Promise<main.HookHealth>;

export function SetCodexHookEnabled(arg1:boolean):Promise<main.HookHealth>;

export function SetCompactNudgesEnabled(arg1:boolean):Promise<void>;
