// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountStatus() {
  return window['go']['main']['App']['GetAccountStatus']();
}

export function GetCompactNudgesEnabled() {
  return window['go']['main']['App']['GetCompactNudgesEnabled']();
}

export function GetHookHealth() {
  return window['go']['main']['App']['GetHookHealth']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessionStats(arg1) {
  return window['go']['main']['App']['GetSessionStats'](arg1);
}

export function GetSiteBaseURL() {
  return window['go']['main']['App']['GetSiteBaseURL']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenBillingPortal() {
  return window['go']['main']['App']['OpenBillingPortal']();
}

export function OpenPricing() {
  return window['go']['main']['App']['OpenPricing']();
}

export function RefreshEntitlement() {
  return window['go']['main']['App']['RefreshEntitlement']();
}

export function SetClaudeHookEnabled(arg1) {
  return window['go']['main']['App']['SetClaudeHookEnabled'](arg1);
}

export function SetCodexHookEnabled(arg1) {
  return window['go']['main']['App']['SetCodexHookEnabled'](arg1);
}

export function SetCompactNudgesEnabled(arg1) {
  return window['go']['main']['App']['SetCompactNudgesEnabled'](arg1);
}

export function StartBrowserSignIn() {
  return window['go']['main']['App']['StartBrowserSignIn']();
}
