// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SetQuiet(arg1) {
  return window['go']['main']['App']['SetQuiet'](arg1);
}
