// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOverview():Promise<main.Overview>;

export function GetOverviewWindow():Promise<main.Overview>;

export function GetProjects():Promise<Array<main.ProjectRow>>;

export function GetSessionStats(arg1:string):Promise<Array<main.SessionRow>>;

export function GetSettings():Promise<main.Settings>;

export function SetQuiet(arg1:boolean):Promise<void>;
