// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {appauth} from '../models';

export function CheckForUpdate():Promise<main.UpdateStatus>;

export function GetAccountStatus():Promise<appauth.Status>;

export function GetCompactNudgesEnabled():Promise<boolean>;

export function GetHookHealth():Promise<main.HookHealth>;

export function GetOverview():Promise<main.Overview>;

export function GetPlatform():Promise<string>;

export function GetProjects():Promise<Array<main.ProjectRow>>;

export function GetSessionStats(arg1:string):Promise<Array<main.SessionRow>>;

export function GetSiteBaseURL():Promise<string>;

export function Logout():Promise<appauth.Status>;

export function OpenBillingPortal():Promise<void>;

export function OpenDataFolder():Promise<void>;

export function OpenPricing():Promise<void>;

export function OpenReleaseNotes():Promise<void>;

export function OpenUpdateRelease(arg1:string):Promise<void>;

export function RefreshEntitlement():Promise<appauth.Status>;

export function SetClaudeHookEnabled(arg1:boolean):Promise<main.HookHealth>;

export function SetCodexHookEnabled(arg1:boolean):Promise<main.HookHealth>;

export function SetCompactNudgesEnabled(arg1:boolean):Promise<void>;

export function StartBrowserSignIn():Promise<appauth.Status>;

export function StartFreeTrial():Promise<appauth.Status>;

export function UninstallWinglet():Promise<boolean>;
